---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  fixme:
    enabled: true
  radon:
    enabled: true
  shellcheck:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
  - "**.sh"
  - "**.md"
exclude_paths:
- test/
- tools/dev_tools/**/*
- src/avrocpp/**/*
