sudo: required
dist: trusty
language: cpp
branches:
  only:
    - master
    - develop
git:
  submodules: false

matrix:
  include:
    - compiler: gcc
      env: INSTALL="" BOOST= FLAGS="--coverage" TESTS=RMF TEST_SETUP= BUILD="Debug"
    - compiler: clang
      env: INSTALL="libhdf5-dev liblog4cxx10-dev" BOOST= FLAGS="--coverage" TESTS=RMF TEST_SETUP= BUILD="Debug"
    - compiler: clang
      env: INSTALL="" BOOST= FLAGS="--coverage" TESTS=RMF TEST_SETUP= BUILD="Debug"

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libboost$BOOST-all-dev swig libc-dbg $INSTALL
 - sudo pip install coverage

script:
 - mkdir build
 - cd build
 - ../tools/coverage/setup.py
 - PYTHONPATH=`pwd`/coverage cmake .. -DCMAKE_BUILD_TYPE="$BUILD" -DCMAKE_CXX_FLAGS="$FLAGS" -DCMAKE_EXE_LINKER_FLAGS="$FLAGS" -DCMAKE_MODULE_LINKER_FLAGS="$FLAGS" -DCMAKE_SHARED_LINKER_FLAGS="$FLAGS" -DIMP_TEST_SETUP=$TEST_SETUP
 - make -j 2
 - export LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
 - ctest -j 2 --output-on-failure -L $TESTS

after_success:
 - (cd coverage && coverage combine && mv .coverage ..)
 - bash <(curl -s https://codecov.io/bash)

# sanitize :-) -fsanitize=address -fno-omit-frame-pointer
# -fsanitize=undefined
#1.48 seems to exist
# [ci skip]
