language: cpp
branches:
  only:
    - master
    - develop
compiler:
  - gcc
  - clang
env:
  - TO_INSTALL=libhdf5-serial-dev BOOST_VERSION=
  - TO_INSTALL= BOOST_VERSION=1.54
git:
  submodules: false

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libboost$BOOST_VERSION-all-dev swig $TO_INSTALL
 - ./setup_git.py

script:
 - mkdir build
 - cd build && cmake -DCMAKE_CXX_FLAGS=-Werr .. && make -j 2
 - cd build && ctest -j 2

# sanitize :-) -fsanitize=address -fno-omit-frame-pointer
# -fsanitize=undefined