language: cpp
branches:
  only:
#    - master
    - develop
compiler:
  - gcc
#  - clang
git:
  submodules: false
# Change this to your needs
before_install:
  - sudo apt-get update && sudo apt-get install libboost-all-dev swig && git submodule update --init --recursive
script:
  - mkdir build && cd build && cmake -DRMF_DEPRECATED_BACKENDS=0 .. && make && ctest
#  - sudo apt-get install hdf5-serial-dev && mkdir build && cd build && cmake -DRMF_DEPRECATED_BACKENDS=1 .. && make && ctest