set(python_examples 
${PROJECT_SOURCE_DIR}/examples/alias.py
${PROJECT_SOURCE_DIR}/examples/all_scores.py
${PROJECT_SOURCE_DIR}/examples/bonds.py
${PROJECT_SOURCE_DIR}/examples/consume.py
${PROJECT_SOURCE_DIR}/examples/create.py
${PROJECT_SOURCE_DIR}/examples/externals.py
${PROJECT_SOURCE_DIR}/examples/geometry.py
${PROJECT_SOURCE_DIR}/examples/make_reference_frames.py
${PROJECT_SOURCE_DIR}/examples/produce.py
${PROJECT_SOURCE_DIR}/examples/reference_frames.py
${PROJECT_SOURCE_DIR}/examples/rmf_decorator.py
${PROJECT_SOURCE_DIR}/examples/rmf_xml.py
)
