sudo: false
language: python
dist: xenial
python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8
matrix:
  include:
    - dist: trusty
      python: 2.6
cache: pip
install: pip install coverage
script: nosetests --with-coverage --cover-branches
after_success:
  - bash <(curl -s https://codecov.io/bash)
