language: python
python:
  - "2.6"
  - "2.7"
  - "3.5"
install: pip install python-coveralls
script: nosetests --with-coverage --cover-package=. --cover-erase
after_success:
  - |
    if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      coveralls
    fi
